// Nextjs Admin/src/components/Sidebar.jsx
"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";
import {
  LayoutDashboard,
  Users,
  Settings,
  Component,
  MousePointerClick,
  FormInput,
  LayoutGrid,
  Bell,
  Navigation,
  Columns,
  FileText,
  Sparkles,
  Monitor,
  Link2,
  ChevronDown,
  ChevronRight,
} from "lucide-react";

const navItems = [
  { href: "/admin/dashboard", label: "Dashboard", icon: LayoutDashboard },
  { href: "/admin/users", label: "Users", icon: Users },
  { href: "/admin/settings", label: "Settings", icon: Settings },
];

const componentCategories = [
  {
    label: "Actions & Interactions",
    icon: MousePointerClick,
    basePath: "/components/actions",
    items: [
      { href: "/components/actions/button", label: "Button" },
      { href: "/components/actions/dropdown", label: "Dropdown" },
      { href: "/components/actions/modal", label: "Modal" },
      { href: "/components/actions/swap", label: "Swap" },
      { href: "/components/actions/theme-controller", label: "Theme Controller" },
      { href: "/components/actions/fab", label: "FAB / Speed Dial" },
      { href: "/components/actions/tooltip", label: "Tooltip" },
      { href: "/components/actions/validator", label: "Validator" },
    ],
  },
  {
    label: "Forms",
    icon: FormInput,
    basePath: "/components/forms",
    items: [
      { href: "/components/forms/input", label: "Text Input" },
      { href: "/components/forms/textarea", label: "Textarea" },
      { href: "/components/forms/checkbox", label: "Checkbox" },
      { href: "/components/forms/radio", label: "Radio" },
      { href: "/components/forms/toggle", label: "Toggle" },
      { href: "/components/forms/select", label: "Select" },
      { href: "/components/forms/file-input", label: "File Input" },
      { href: "/components/forms/range", label: "Range Slider" },
      { href: "/components/forms/rating", label: "Rating" },
      { href: "/components/forms/label", label: "Label" },
      { href: "/components/forms/fieldset", label: "Fieldset" },
      { href: "/components/forms/filter", label: "Filter" },
    ],
  },
];

export default function Sidebar({ collapsed }) {
  const pathname = usePathname();
  const [openCategories, setOpenCategories] = useState(() => {
    // Open the category that contains the current path
    const activeCategory = componentCategories.find((cat) =>
      pathname.startsWith(cat.basePath)
    );
    return activeCategory ? [activeCategory.basePath] : [];
  });

  const toggleCategory = (basePath) => {
    setOpenCategories((prev) =>
      prev.includes(basePath)
        ? prev.filter((p) => p !== basePath)
        : [...prev, basePath]
    );
  };

  return (
    <aside
      className={`bg-base-100 text-base-content border-r border-base-200 flex-shrink-0 overflow-hidden
      fixed inset-y-0 left-0 z-40 transform transition-[transform,width] duration-300 ease-in-out md:fixed md:inset-y-0 md:left-0 md:translate-x-0
      ${collapsed ? "-translate-x-full md:w-20" : "translate-x-0 w-72"}`}
    >
      <div className="flex items-center gap-3 px-4 py-4 border-b border-base-200">
        <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-primary text-primary-content font-bold">
          AD
        </div>
        {!collapsed && (
          <div className="flex flex-col">
            <span className="font-semibold tracking-tight">Admin Panel</span>
            <span className="text-xs text-base-content/60">
              Next.js + DaisyUI
            </span>
          </div>
        )}
      </div>

      <nav className="menu flex flex-col flex-nowrap w-full p-2 pr-3 md:p-4 text-sm overflow-y-auto overflow-x-hidden max-h-[calc(100vh-80px)]">
        {/* Main Navigation */}
        {!collapsed && (
          <p className="menu-title text-xs uppercase tracking-wide text-base-content/60">
            Main
          </p>
        )}
        {navItems.map((item) => {
          const Icon = item.icon;
          const active = pathname.startsWith(item.href);
          return (
            <li key={item.href}>
              <Link href={item.href} className={active ? "active" : undefined}>
                <Icon className="h-4 w-4" />
                {!collapsed && <span>{item.label}</span>}
              </Link>
            </li>
          );
        })}

        {/* Components Section */}
        {!collapsed && (
          <p className="menu-title text-xs uppercase tracking-wide text-base-content/60 mt-4">
            Components
          </p>
        )}
        {collapsed && <div className="divider my-2"></div>}


        {/* Category Dropdowns */}
        {componentCategories.map((category) => {
          const Icon = category.icon;
          const isOpen = openCategories.includes(category.basePath);
          const isActive = pathname.startsWith(category.basePath);

          if (collapsed) {
            // When collapsed, just show icon linking to first item
            return (
              <li key={category.basePath}>
                <Link
                  href={category.items[0]?.href || category.basePath}
                  className={isActive ? "active" : undefined}
                  title={category.label}
                >
                  <Icon className="h-4 w-4" />
                </Link>
              </li>
            );
          }

          return (
            <li key={category.basePath}>
              <details open={isOpen}>
                <summary
                  onClick={(e) => {
                    e.preventDefault();
                    toggleCategory(category.basePath);
                  }}
                  className={`cursor-pointer ${isActive ? "font-medium" : ""}`}
                >
                  <Icon className="h-4 w-4" />
                  <span>{category.label}</span>
                </summary>
                <ul className="flex flex-col">
                  {category.items.map((item) => {
                    const itemActive = pathname === item.href;
                    return (
                      <li key={item.href}>
                        <Link
                          href={item.href}
                          className={itemActive ? "active" : undefined}
                        >
                          {item.label}
                        </Link>
                      </li>
                    );
                  })}
                </ul>
              </details>
            </li>
          );
        })}
      </nav>
    </aside>
  );
}

// Vue Admin/src/components/layout/Sidebar.vue
<template>
  <aside
    class="bg-base-100 min-h-screen transition-all duration-200 border-r border-slate-200"
    :class="collapsed ? 'w-16' : 'w-56'"
  >
    <!-- Header / Branding -->
    <div class="flex items-center gap-2 p-3">
      <div
        class="w-8 h-8 rounded-lg bg-primary text-primary-content flex items-center justify-center"
      >
        <component :is="icons.LayoutDashboard" class="w-4 h-4" />
      </div>

      <span v-if="!collapsed" class="font-bold tracking-wide">
        Admin
      </span>
    </div>

    <!-- Menu -->
    <nav class="p-2 space-y-1">
      <div
        v-for="item in menuItems"
        :key="item.fullPath"
        class="relative group"
      >
        <!-- PARENT BUTTON -->
        <button
          class="btn btn-sm w-full justify-between"
          :class="isParentActive(item) ? 'btn-primary' : 'btn-ghost'"
          @click="toggle(item)"
        >
          <div class="flex items-center gap-2">
            <component
              :is="icons[item.icon] || icons.HelpCircle"
              class="w-5 h-5"
            />
            <span v-if="!collapsed">{{ item.label }}</span>
          </div>

          <!-- CHEVRON (expanded only) -->
          <component
            v-if="item.children?.length && !collapsed"
            :is="icons.ChevronDown"
            class="w-4 h-4 transition-transform duration-200"
            :class="isOpen(item.fullPath) ? 'rotate-180' : ''"
          />
        </button>

        <!-- CHILDREN (EXPANDED MODE) -->
        <transition
          enter-active-class="transition-all duration-200 ease-out"
          enter-from-class="opacity-0 max-h-0"
          enter-to-class="opacity-100 max-h-40"
          leave-active-class="transition-all duration-150 ease-in"
          leave-from-class="opacity-100 max-h-40"
          leave-to-class="opacity-0 max-h-0"
        >
          <div
            v-if="isOpen(item.fullPath) && !collapsed"
            class="ml-6 mt-1 space-y-1 overflow-hidden"
          >
            <RouterLink
              v-for="child in item.children"
              :key="child.fullPath"
              :to="child.fullPath"
              class="btn btn-xs w-full justify-start"
              :class="isChildActive(child.fullPath)"
            >
              {{ child.label }}
            </RouterLink>
          </div>
        </transition>

        <!-- CHILDREN (COLLAPSED MODE - HOVER CARD) -->
        <div
          v-if="collapsed && item.children?.length && isParentActive(item)"
          class="absolute left-16 top-1/2 -translate-y-1/2 z-[9999]"
        >
          <div
            class="bg-base-100 shadow-2xl rounded-xl p-3 min-w-[220px]
                   border border-base-300
                   transition-all duration-200 ease-out"
          >
            <!-- Header -->
            <div class="font-semibold text-sm mb-2 px-2">
              {{ item.label }}
            </div>

            <!-- Links -->
            <div class="space-y-1">
              <RouterLink
                v-for="child in item.children"
                :key="child.fullPath"
                :to="child.fullPath"
                class="btn btn-xs w-full justify-start"
                :class="isChildActive(child.fullPath)"
              >
                {{ child.label }}
              </RouterLink>
            </div>
          </div>
        </div>
      </div>
    </nav>
  </aside>
</template>

<script setup>
import { computed, ref, watch } from 'vue'
import { useRoute, useRouter, RouterLink } from 'vue-router'
import * as Icons from 'lucide-vue-next'

const props = defineProps({
  collapsed: {
    type: Boolean,
    default: false
  }
})

const router = useRouter()
const route = useRoute()

const openParents = ref({})

/* ICON MAP — ALL LUCIDE ICONS */
const icons = Icons

/* BUILD MENU FROM ROUTER */
const menuItems = computed(() => {
  const root = router.options.routes.find(r => r.path === '/')
  if (!root?.children) return []

  return root.children
    .filter(r => r.meta?.sidebar)
    .map(r => ({
      label: r.meta.sidebar,
      icon: r.meta.icon,
      fullPath: r.path === '' ? '/' : `/${r.path}`,
      children: (r.children || [])
        .filter(c => c.meta?.sidebar)
        .map(c => ({
          label: c.meta.sidebar,
          fullPath: `/${r.path}/${c.path}`
        }))
    }))
})

/* STATE HELPERS */
function isOpen(path) {
  return openParents.value[path]
}

function isParentActive(item) {
  return (
    route.path === item.fullPath ||
    route.path.startsWith(item.fullPath + '/')
  )
}

function isChildActive(path) {
  return route.path === path
    ? 'btn-primary'
    : 'btn-ghost'
}

/* CLICK BEHAVIOR */
function toggle(item) {
  if (!item.children?.length) {
    router.push(item.fullPath)
    return
  }

  openParents.value[item.fullPath] =
    !openParents.value[item.fullPath]
}

/* ACCORDION MODE: AUTO OPEN ACTIVE, CLOSE OTHERS */
watch(
  () => route.path,
  () => {
    const newState = {}

    menuItems.value.forEach(item => {
      if (
        route.path === item.fullPath ||
        route.path.startsWith(item.fullPath + '/')
      ) {
        newState[item.fullPath] = true
      } else {
        newState[item.fullPath] = false
      }
    })

    openParents.value = newState
  },
  { immediate: true }
)
</script>
